- set_fact:
    podman_packages: [
      aardvark-dns,  # Required for DNS between podman-compose containers
      podman-dnsname,
      podman-docker,
      podman,
    ]

- set_fact:
    docker_packages: [
      docker,
    ]

- name: Install development packages
  kewlfft.aur.aur:
    name: [
      cmake,
      direnv,
      github-cli,
      go,
      imagemagick,  # Contains convert
      kubectl,
      make,
      nodejs,
      npm,
      pacman-contrib,  # Package build utils like updpkgsums
      potrace,  # Convert to svg
      python-pip,
      python-setuptools,
      python-virtualenv,
      python-virtualenvwrapper,
      python,
      tmux,
    ]
    state: present

- block:
  - name: Remove podman packages
    package:
      name: "{{ podman_packages }}"
      state: absent
    become: true

  - name: Install docker packages
    kewlfft.aur.aur:
      name: "{{ docker_packages }}"
      state: present
    become: true
  when: container_runtime == "docker"

- block:
  - name: Remove docker packages
    kewlfft.aur.aur:
      name: "{{ docker_packages }}"
      state: absent
    become: true

  - name: Install podman packages
    kewlfft.aur.aur:
      name: "{{ podman_packages }}"
      state: present
    become: true
  when: container_runtime == "podman"
