---
- name: Install packages for nginx
  apt:
    state: present
    name: [nginx, certbot, python-certbot-nginx]
  become: yes
  become_user: root

- name: Place generic nginx configs
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
  with_items:
    - ssl-options.conf
    - phphandler.conf
  become: yes
  become_user: root
  notify: reload-nginx

- name: Add renew cron for certbot
  cron:
    name: Certbot renewal
    job: /usr/bin/certbot renew
    user: root
    weekday: "0"
    minute: "42"
    hour: "9"
    cron_file: /etc/cron.d/certbot
  become: yes
  become_user: root
