- name: Install generic component on whole cluster
  hosts: k3s
  tasks:
    - include_role: name=k3s-common

- name: Manage K3S servers
  hosts: k3s_servers
  tasks:
    - include_role: name=k3s-master

- name: Manage k3s agents
  hosts: k3s_agents
  tasks:
    - include_role: name=k3s-slave
