---
- name: Install generic component on whole cluster
  hosts: k3s
  roles:
    - k3s/common

- name: Manage K3S servers
  hosts: k3s_servers
  roles:
    - k3s/server

- name: Manage k3s agents
  hosts: k3s_agents
  roles:
    - k3s/agent

- name: Manage k3s apps
  hosts: "{{ groups['k3s_servers'].0 }}"
  roles:
    - k3s/apps
