---
collections:
- community.general  # Contains ufw, pacman
- gluster.gluster
- kewlfft.aur  # Contains AUR installers like yay
- kubernetes.core
- community.docker  # Contains swarm
- ansible.posix  # Contains authorized_key
