---
- name: restart-tailscaled
  service:
    name: tailscaled
    state: restarted
  become: yes
  become_user: root

- name: restart-fail2ban
  service:
    name: fail2ban
    state: restarted
  become: yes
  become_user: root

- name: reload-ssh
  service:
    name: sshd
    state: reloaded
  become: yes
  become_user: root

- name: reload-ufw
  command: ufw reload
  become: yes

- name: restart-syncthing
  systemd:
    name: syncthing
    state: restarted
    daemon_reload: yes
    enabled: yes
    scope: user

- name: restart-fwupd
  systemd:
    name: fwupd
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true
