---
- name: restart-tailscaled
  service:
    name: tailscaled
    state: restarted
  become: yes
  become_user: root

- name: restart-fail2ban
  service:
    name: fail2ban
    state: restarted
  become: yes
  become_user: root

- name: reload-ssh
  service:
    name: ssh
    state: reloaded
  become: yes
  become_user: root

- name: reload-ufw
  command: ufw reload
  become: yes
