---
- name: Join k3s as slave
  command:
  args:
    argv:
      - k3sup
      - join
      - --ip
      - "{{ tailscale_ip }}"
      - --server-ip
      - "{{ k3s_servers.0.tailscale_ip }}"
      - --user
      - alex
      - --ssh-key
      - .ssh/id_ed25519
  register: slave_created
  delegate_to: localhost

- name: Debug report of slave creation
  debug: var=slave_created
  when: slave_created is failed

- name: Check API availability of slave servers
  uri:
    url: "https://{{ tailscale_ip }}:6443"
    method: GET
    validate_certs: False
    status_code: 401
    body_format: json
  register: http_api_result
  retries: 6
  delay: 15
  until: http_api_result is not failed
  when: slave_created is succeeded

- name: Debug report of API availability
  debug: var=http_api_result
  when: http_api_result is failed
