---
- name: Install core packages
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  become_user: root
  vars:
    packages:
    - python-pip
    - python3
    - python3-distutils
    - cmake
    - htop
    - python3-venv
    - fd-find

- name: Install Python packages
  pip:
      name: "{{ packages }}"
  vars:
    packages:
    - virtualenvwrapper
    - flake8
