---
- name: Install core packages
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-pip
    - python3
    - python3-distutils

- name: Install virtualenvwrapper
  pip: name=virtualenvwrapper
