---
- name: Install core packages
  apt: 
    name: "{{ packages }}"
    state: present
  become: yes
  become_user: root
  vars:
    packages:
    - python-pip
    - python3
    - python3-distutils
    - cmake

- name: Install virtualenvwrapper
  pip: name=virtualenvwrapper
