---
- name: Install core packages
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  become_user: root
  vars:
    packages:
    - python-pip
    - python3
    - python3-distutils
    - cmake
    - htop
    - python3-venv

- name: Install debian buster core packages
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  become_user: root
  vars:
    packages:
    - fd-find
  failed_when: false

- name: Install Python packages
  pip:
      name: "{{ packages }}"
  vars:
    packages:
    - virtualenvwrapper
    - flake8
  register: pip_installs

- name: Symlink virtualenvwrapper.sh
  file:
    src: bla
    dest: /home/alex/.local/bin/virtualenvwrapper.sh
    state: link
  when: pip_installs.changed
