---
- name: Install packages for desktop
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  become_user: root
  vars:
    packages:
    - x11-xserver-utils
    - xcb
    - libcairo2-dev
    - libxcb-util0-dev
    - libxcb-randr0-dev
    - libxcb-composite0-dev
    - python-xcbgen
    - xcb-proto
    - libxcb-image0-dev
    - libxcb1-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-xkb-dev
    - libxcb-xrm-dev
    - libxcb-cursor-dev
    - libasound2-dev
    - libpulse-dev
    - libjsoncpp-dev
    - libmpdclient-dev
    - libcurl4-openssl-dev
    - libiw-dev
    - libnl-genl-3-dev
    - i3
    - compton
    - zsh

- name: Clone oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=/home/alex/.oh-my-zsh

- name: Set zsh as default shell
  command: chsh -s /usr/bin/zsh alex
  become: yes
  become_user: root

- name: Install fonts
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  become_user: root
  vars:
    packages:
    - fonts-powerline
    - fonts-font-awesome
  register: fonts_installed

- name: Reset font cache
  command: fc-cache -fv
  when: fonts_installed.changed

- name: Clone polybar repo
  git:
    repo: https://github.com/jaagr/polybar
    dest: ~/.apps/polybar
    accept_hostkey: yes
    update: no
    version: 3.2
    recursive: yes
  register: polybar_clone

- name: Create polybar build directory
  file:
    path: ~/.apps/polybar/build
    state: directory
  when: polybar_clone.changed

- name: Set up polybar
  command: ./build.sh chdir="~/.apps/polybar"
  changed_when: false
  when: polybar_clone.changed

- name: Create wallpapers directory
  file:
    path: ~/wallpapers
    state: directory

- name: Download wallpapers
  command: ~/scripts/download_wallpapers.py chdir="~/wallpapers"
