---
- name: Install packages for desktop
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  become_user: root
  vars:
    packages:
    - x11-xserver-utils
    - xcb
    - libcairo2-dev
    - libxcb-util0-dev
    - libxcb-randr0-dev
    - libxcb-composite0-dev
    - python-xcbgen
    - xcb-proto
    - libxcb-image0-dev
    - libxcb1-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-xkb-dev
    - libxcb-xrm-dev
    - libxcb-cursor-dev
    - libasound2-dev
    - libpulse-dev
    - libjsoncpp-dev
    - libmpdclient-dev
    - libcurl4-openssl-dev
    - libiw-dev
    - libnl-genl-3-dev
    - i3
    - py3status
    - compton
    - zsh
    - scrot
    - python3-lxml  # Needed for Download wallpapers task
    - imagemagick  # Needed for i3lock-fancy's convert command

- name: Clone oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=/home/alex/.oh-my-zsh

- name: Set zsh as default shell
  command: chsh -s /usr/bin/zsh alex
  become: yes
  become_user: root

- name: Install fonts
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  become_user: root
  vars:
    packages:
    - fonts-powerline
    - fonts-font-awesome
  register: fonts_installed

  # TODO: refactor this to a handler
- name: Reset font cache
  command: fc-cache -fv
  when: fonts_installed.changed

- name: Create wallpapers directory
  file:
    path: ~/wallpapers
    state: directory

  # TODO: don't download when not necessary
- name: Download wallpapers
  command: ~/scripts/download_wallpapers.py chdir="~/wallpapers"

- name: Clone i3lock-fancy
  git:
    repo=https://github.com/AlexanderGrooff/i3lock-fancy
    dest=/home/alex/code/i3lock-fancy
    version=dualmonitors
  register: i3lock_clone

- name: Build i3lock-fancy
  command: sudo make install chdir="/home/alex/code/i3lock-fancy"
  when: i3lock_clone.changed
