---
- name: Install vim-gtk3 package
  apt: 
    name: vim-gtk3
  become: yes
  become_user: root

- name: Check if vundle is installed
  stat:
    path: ~/.vim/bundle/Vundle.vim
  register: vundle

- name: Clone vundle package
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
  when: vundle.stat.exists == false

- name: Clone fzf package
  git: repo=https://github.com/junegunn/fzf.git depth=1 update=no dest=~/.apps/fzf
  register: fzf_updated

- name: Install fzf
  command: ~/.apps/fzf/install
  when: fzf_updated.changed
