---
- name: Check if k3s-agent is already running
  service:
    name: k3s-agent
    state: started
  register: start_k3s_agent
  failed_when: false  # Will error if not installed, that's fine

- include: install.yml
  when: not start_k3s is succeeded
