---
- name: restart plex
  service:
    name: plexmediaserver
    state: restarted
  become: yes
  become_user: root

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  become: yes
  become_user: root
