---
- name: Install yay
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present

- name: Install core packages
  kewlfft.aur.aur:
    name: [
      aardvark-dns,  # Required for DNS between podman-compose containers
      autossh,
      cmake,
      cronie,
      cue,  # Configuration language
      curl,
      direnv,
      dnsutils,
      fd,
      git,
      go,
      htop,
      inetutils,  # Contains telnet
      jq,
      keychain,
      lshw,
      make,
      man-db,
      net-tools,  # Contains netstat
      nmap,
      nodejs,
      npm,
      openvpn,
      podman-dnsname,
      podman-docker,
      podman,
      python-pip,
      python-setuptools,
      python-virtualenv,
      python-virtualenvwrapper,
      python,
      rsync,
      sudo,
      syncthing,
      tmux,
      traceroute,
      ufw,
      unzip,
      vim,
      xsel,
      zsh,
    ]
    state: present

- include: podman.yml
