---
- name: Install yay
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present

- name: Install core packages
  kewlfft.aur.aur:
    name: [
      aardvark-dns,  # Required for DNS between podman-compose containers
      autossh,
      cmake,
      cronie,
      cue,  # Configuration language
      curl,
      direnv,
      dnsutils,
      fd,
      fwupd,
      github-cli,
      git,
      go,
      htop,
      inetutils,  # Contains telnet
      jq,
      keychain,
      kubectl,
      lshw,
      make,
      man-db,
      net-tools,  # Contains netstat
      nmap,
      nodejs,
      npm,
      openvpn,
      podman-dnsname,
      podman-docker,
      podman,
      python-pip,
      python-setuptools,
      python-virtualenv,
      python-virtualenvwrapper,
      python,
      rsync,
      sudo,
      syncthing,
      tmux,
      traceroute,
      ufw,
      unzip,
      vim,
      xclip,
      xsel,
      yq,
      zsh,
    ]
    state: present

- name: Place fwupd config
  copy:
    src: etc/fwupd/uefi_capsule.conf
    dest: /etc/fwupd/uefi_capsule.conf
    mode: 0644
    owner: root
    group: root
  become: true
  notify: [restart-fwupd]

- name: Enable services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  become: true
  with_items:
    - cronie
    - fwupd
    - ufw

- include: podman.yml
