---
- name: Install yay
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present

- name: Install core packages
  kewlfft.aur.aur:
    name: [
      cmake,
      curl,
      dnsutils,
      docker
      git,
      htop,
      keychain,
      net-tools,  # Contains netstat
      nodejs,
      npm,
      python-pip,
      python-setuptools,
      python-virtualenv,
      python-virtualenvwrapper,
      python,
      sudo,
      traceroute,
      ufw,
      unzip,
      vim,
      zsh,
    ]
    state: present
