---
- name: Install yay
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present

- name: Install core packages
  kewlfft.aur.aur:
    name: [
      autossh,
      cmake,
      curl,
      direnv,
      dnsutils,
      docker,
      fd,
      git,
      htop,
      jq,
      keychain,
      make,
      man-db,
      net-tools,  # Contains netstat
      nmap,
      nodejs,
      npm,
      python-pip,
      python-setuptools,
      python-virtualenv,
      python-virtualenvwrapper,
      python,
      sudo,
      tmux,
      traceroute,
      ufw,
      unzip,
      vim,
      zsh,
      xsel,
    ]
    state: present
