---
- include: arch/core.yml
- include: arch/dev.yml
  when: development.enable

- include: arch/graphics.yml
  when: desktop.graphics.enable|default(false)

- include: podman.yml
  when: development.enable and container_runtime == "podman"

- include: docker.yml
  when: development.enable and container_runtime == "docker"
