---
- include: debian/go.yml
  when: development.enable

- name: Install core packages
  apt:
    name: [
      autossh,
      apparmor,
      curl,
      gpg-agent,  # Required for apt-key
      gpg,
      htop,
      iperf3,
      jq,
      keychain,
      python3-pip,
      python3,
      sudo,
      ufw,
      unzip,
      vim,
      xsel,
      zsh,
    ]
    state: latest
    update_cache: yes
  become: true
  become_user: root

- name: Install dev packages
  apt:
    name: [
      binutils,  # Commands like `strings`
      cmake,
      direnv,
      dnsutils,
      git,
      make,
      net-tools,  # Contains netstat
      nmap,
      nodejs,
      npm,
      python3-distutils,
      python3-setuptools,
      traceroute,
      virtualenv,
      virtualenvwrapper,
    ]
    state: latest
    update_cache: yes
  become: true
  become_user: root
  when: development.enable

- name: Install binaries with go
  command: /usr/local/go/bin/go install cuelang.org/go/cmd/cue@latest
  args:
    creates: /home/alex/go/bin/cue
  when: development.enable

- name: Remove redundant packages
  apt:
    name: [
      snapd
    ]
    state: absent
  become: yes

  # TODO: only try to install on buster
  # TODO: install 'fd' on distros other than buster
- name: Install debian buster core packages
  apt:
    name: [fd-find]
    state: present
  become: yes
  become_user: root
  failed_when: false

- name: Symlink python to python3
  command: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
  become: yes

- name: Symlink pip to pip3
  command: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
  become: yes

- name: Download kubectl
  get_url:
    url: https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755
    owner: root
  become: yes
  when: development.enable

- include: debian/rust.yml
  when: development.enable
- include: debian/syncthing.yml
- include: debian/docker.yml
