---
- name: Add alacritty repo GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 5B7FC40A404FAD98548806028AC9B4BBBAB4900B
  become: yes

- name: Add alacritty apt repo
  apt_repository:
    repo: ppa:mmstick76/alacritty
  become: yes

- name: Define desktop packages
  set_fact:
    desktop_packages: [
      alacritty,
      flameshot,
      fonts-font-awesome,
      kde-plasma-desktop,
      libfontconfig1-dev,
      libfreetype6-dev,
      libxcb-xfixes0-dev,
      libxkbcommon-dev,
      pavucontrol,
      pkg-config,
      sddm,
    ]

- name: Define i3 packages
  set_fact:
    i3_packages: [
      autorandr,
      i3-wm,
      i3lock,
      py3status,
      rofi,
    ]

- name: Define kdm packages
  set_fact:
    kde_packages: [
      kwin-bismuth,  # WM
    ]

- name: Define redundant packages
  set_fact:
    redundant_desktop_packages: [
      gdm3,
      gnome-desktop3-data,
      gnome-shell,  # Not sure if this is the actual gnome package
    ]

- name: Install generic desktop packages for Debian
  apt:
    name: "{{ desktop_packages }}"
  become: true
  when: ansible_os_family == "Debian"

- name: Remove redundant desktop packages for Debian
  apt:
    name: "{{ redundant_desktop_packages }}"
    state: absent
  become: true
  when: ansible_os_family == "Debian"

- name: Install generic desktop packages for Arch
  kewlfft.aur.aur:
    name: "{{ desktop_packages }}"
  become: true
  when: ansible_distribution == "Archlinux"

- name: Remove redundant desktop packages for Arch
  kewlfft.aur.aur:
    name: "{{ redundant_desktop_packages }}"
  become: true
  when: ansible_distribution == "Archlinux"

- name: Manage i3wm
  block:
    - name: Install desktop packages for Arch
      kewlfft.aur.aur:
        name: [
        ]
        state: present
      become: true
      when: ansible_distribution == "Archlinux"

    - name: Install desktop packages for Debian
      apt:
        name: "{{ i3_packages }}"
        state: latest
      become: true
      when: ansible_os_family == "Debian"

    - name: Install i3 pip packages
      pip:
        name: [
          i3-cycle
        ]
        state: latest

    - name: Remove kde packages
      apt:
        name: "{{ kde_packages }}"
        state: absent
      become: yes
  when: desktop.wm == "i3"

- name: Manage Sway
  block:
    - name: Install sway
      apt:
        name: [
          grimshot,  # Screenshot tool
          sway,
          swaylock,
          wdisplays,
          weston,  # Compositor
        ]
        state: latest
      become: true
      when: ansible_os_family == "Debian"
  when: desktop.wm == "sway"

- name: Manage KDE
  block:
  # Docs at https://volian.org/bismuth/
  - name: Add Bismuth GPG apt Key
    apt_key:
      url: https://deb.volian.org/volian/scar.key
      state: present
    when: ansible_os_family == "Debian"
    become: yes

  - name: Add Bismuth Repository
    apt_repository:
      repo: "deb http://deb.volian.org/volian/ scar main"
      state: present
    when: ansible_os_family == "Debian"
    become: yes

  - name: Install kde packages
    apt:
      name: "{{ kde_packages }}"
      state: latest
    become: yes

  - name: Remove i3 packages
    apt:
      name: "{{ i3_packages }}"
      state: absent
    become: yes
  when: desktop.wm == "kde"

- name: Create user service directory
  file:
    path: /home/alex/.config/systemd/user/
    state: directory
    recurse: yes
    owner: alex
    group: alex

- name: Place user service files
  template:
    src: config/systemd/user/hnproxy.service
    dest: /home/alex/.config/systemd/user/hnproxy.service
    owner: alex
    group: alex

- name: Start hnproxy service
  systemd:
    name: hnproxy
    state: started
    enabled: yes
    scope: user
    daemon_reload: yes
