---
- name: Install desktop packages for Arch
  kewlfft.aur.aur:
    name: [
      py3status,
      i3-wm,
      sakura
    ]
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install desktop packages for Arch
  kewlfft.aur.aur:
    name: [
      py3status,
      i3-wm,
      sakura
    ]
    state: present
  when: ansible_distribution == "Archlinux"
