---
- name: Add alacritty repo GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 5B7FC40A404FAD98548806028AC9B4BBBAB4900B
  become: yes
  when: ansible_os_family == "Debian"

- name: Add alacritty apt repo
  apt_repository:
    repo: ppa:mmstick76/alacritty
  become: yes
  when: ansible_os_family == "Debian"

- name: Define desktop packages
  set_fact:
    desktop_packages: [
      alacritty,
      cups,
      flameshot,
      pavucontrol,
      pkg-config,
      thunar,
    ]

- name: Define Debian specific desktop packages
  set_fact:
    debian_desktop_packages: [
      fonts-font-awesome,
      libfontconfig1-dev,
      libfreetype6-dev,
      libxcb-xfixes0-dev,
      libxkbcommon-dev,
      network-manager-gnome,  # Contains nm-applet
    ]

- name: Define arch specific desktop packages
  set_fact:
    arch_desktop_packages: [
      1password,
      accountsservice,  # Fixes lightdm error
      aconfmgr-git,
      bluez-utils,
      bluez,
      dconf-editor,
      gnome-keyring,  # https://github.com/MicrosoftDocs/live-share/issues/224#issuecomment-383324321
      libimobiledevice,  # iPhone USB tethering
      nm-connection-editor,  # Networkmanager GUI
      obsidian,
      rofi-emoji,
      seahorse,  # Gnome keyring GUI
      slack-desktop,
      ttf-font-awesome,
      ttf-jetbrains-mono-nerd,
      usbutils,  # lsusb
      usbmuxd,  # iPhone USB tethering
      visual-studio-code-bin,
      zotero,
    ]

- name: Define i3 packages
  set_fact:
    i3_packages: [
      arandr,
      autorandr,
      dunst,
      i3-wm,
      i3lock,
      py3status,
      rofi,
      xss-lock,  # Locks screen on suspend
    ]

- name: Define kdm packages
  set_fact:
    kde_packages: [
      kde-plasma-desktop,
      kwin-bismuth,  # WM
    ]

- name: Define redundant packages for Debian
  set_fact:
    debian_redundant_desktop_packages: [
      gnome-desktop3-data,
      gnome-shell,  # Not sure if this is the actual gnome package
    ]

- name: Define redundant packages for Arch
  set_fact:
    arch_redundant_desktop_packages: [
      xterm,  # Default i3 terminal
    ]

- name: Install generic desktop packages for Debian
  apt:
    name: "{{ desktop_packages }}"
  become: true
  when: ansible_os_family == "Debian"

- name: Install specific desktop packages for Debian
  apt:
    name: "{{ debian_desktop_packages }}"
  become: true
  when: ansible_os_family == "Debian"

# TODO: The concept works but somehow the keyserver is required.
# I don't know what the fix is, but these keys need to be imported
# for yay to accept the package.
# - name: Accept AUR gpg keys
#   community.general.pacman_key:
#     id: "{{ item }}"
#     keyserver: "https://keys.openpgp.org/"
#     state: present
#   become: true
#   with_items:
#   - 3FEF9748469ADBE15DA7CA80AC2D62742012EA22  # 1password

- name: Install generic desktop packages for Arch
  kewlfft.aur.aur:
    name: "{{ desktop_packages }}"
  become: true
  when: ansible_os_family == "Archlinux"

- name: Install specific desktop packages for Arch
  kewlfft.aur.aur:
    name: "{{ arch_desktop_packages }}"
  when: ansible_distribution == "Archlinux"

- name: Remove redundant desktop packages for Debian
  apt:
    name: "{{ debian_redundant_desktop_packages }}"
    state: absent
  become: true
  when: ansible_os_family == "Debian"

- name: Remove redundant desktop packages for Arch
  pacman:
    name: "{{ arch_redundant_desktop_packages }}"
    state: absent
  become: yes
  when: ansible_distribution == "Archlinux"

- include: "desktop/{{ desktop.wm }}.yml"

- name: Symlink ssh-askpass
  file:
    src: /usr/lib/seahorse/ssh-askpass
    dest: /usr/lib/ssh/ssh-askpass
    state: link
  become: yes
  when: ansible_distribution == "Archlinux"

- name: Set default applications for xdg-open
  lineinfile:
    path: ~/.config/mimeapps.list
    line: "{{ item }}"
    state: present
    insertafter: "[Added Associations]"
  loop:
  - "text/html=firefox.desktop"
  - "x-scheme-handler/http=firefox.desktop"
  - "x-scheme-handler/https=firefox.desktop"
  - "inode/directory=thunar.desktop"

- name: Activate user service files
  include: includes/user_service.yml
  loop:
  - hnproxy
  - wakelock
  loop_control:
    loop_var: service_name

# Disable system beep
- name: Blacklist pcspkr
  template:
    src: etc/modprobe.d/nobeep.conf
    dest: /etc/modprobe.d/nobeep.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Start cups service
  systemd:
    name: cups
    state: started
    enabled: yes
  become: true

- include: fingerprint.yml

# If you want to remove proprietary stuff to avoid asking for a Lens ID, you
# can delete the folder /usr/share/lens/resources/extensions/lenscloud*
# sudo rm -vr /usr/share/lens/resources/extensions/lenscloud*
