- name: Add user to Docker group
  user:
    name: alex
    groups:
      - docker
    append: yes
  become: yes
  tags: [users]

- name: Enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
