---
- name: Install fail2ban
  apt:
      name: fail2ban
      state: present
      update_cache: yes
  notify: restart-fail2ban

- name: ensure that fail2ban is running and enabled
  service: name=fail2ban enabled=yes state=started

- name: Set jail.local
  template:
    src: fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
  notify: restart-fail2ban
