---
- name: Check if fingerprint reader is present
  shell: lsusb | grep -i "Fingerprint Reader"
  failed_when: false
  changed_when: false
  register: fingerprint_reader

- name: Install Debian fingerprint reader packages
  apt:
    name: [
      fprintd,
      fprintd-gui,
    ]
    state: latest
  become: true
  when: fingerprint_reader.rc == 0 and ansible_os_family == "Debian"

- name: Install Arch fingerprint reader packages
  kewlfft.aur.aur:
    name: [
      fprintd,
    ]
    state: latest
  become: true
  when: fingerprint_reader.rc == 0 and ansible_distribution == "Archlinux"

- name: Remove old login
  lineinfile:
    path: /etc/pam.d/system-local-login
    state: absent
    regexp: "auth sufficient pam_fprintd.so"
  become: true
  when: fingerprint_reader.rc == 0

- name: Allow fingerprint as system login
  lineinfile:
    path: "/etc/pam.d/{{ item }}"
    line: "auth		sufficient  	pam_unix.so try_first_pass likeauth nullok"
    insertafter: "#%PAM-1.0"
  become: true
  when: fingerprint_reader.rc == 0
  with_items:
  - system-local-login
  - lightdm

- name: Start fprintd
  systemd:
    name: fprintd
    enabled: yes
  become: true
  when: fingerprint_reader.rc == 0
