---
- name: Install fail2ban for Debian
  apt:
      name: fail2ban
      state: present
  become: true
  notify: restart-fail2ban
  when: ansible_os_family == "Debian"

- name: Install fail2ban for Archlinux
  kewlfft.aur.aur:
      name: fail2ban
      state: present
  notify: restart-fail2ban
  when: ansible_distribution == "Archlinux"

- name: ensure that fail2ban is running and enabled
  service: name=fail2ban enabled=yes state=started
  become: true

- name: Set jail.local
  template:
    src: fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
  become: true
  notify: restart-fail2ban

- name: Allow access from Tailscale
  community.general.ufw:
    rule: allow
    interface: tailscale0
    direction: in
  become: true
  notify: reload-ufw

- name: Allow traffic on UDP port for Tailscale
  community.general.ufw:
    rule: allow
    port: 41641
    proto: udp
  become: true
  notify: reload-ufw

- name: Default to deny all traffic
  community.general.ufw:
    state: enabled
    policy: deny
  become: true
  notify: reload-ufw

- name: Allow users to read logs
  file:
    path: /var/log/fail2ban.log
    mode: 0644
  become: true
