---
- name: Install iptables persistent
  apt: name=iptables-persistent state=present

- name: Check state of packages
  command: iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

- name: Allow incoming SSH traffic
  command: iptables -I INPUT -p tcp --dport 22 -i eth0 -j ACCEPT

- name: Allow incoming HTTP traffic
  command: iptables -I INPUT -p tcp --dport 80 -i eth0 -j ACCEPT

- name: Allow incoming HTTPS traffic
  command: iptables -I INPUT -p tcp --dport 443 -i eth0 -j ACCEPT

- name: Allow all traffic on loopback device
  command: iptables -I INPUT -i lo -j ACCEPT

- name: Allow all outgoing traffic
  command: iptables -P OUTPUT ACCEPT

- name: Drop all non-specified incoming traffic
  command: iptables -P INPUT DROP

- name: Make v4 rules persistent
  shell: iptables-save > /etc/iptables/rules.v4

- name: Make v6 rules persistent
  shell: ip6tables-save > /etc/iptables/rules.v6
