---
- include: debian.yml
  when: ansible_distribution == "Debian"

- include: arch.yml
  when: ansible_distribution == "Archlinux"

- name: Install Python packages
  pip:
    name: [
        virtualenvwrapper,
        speedtest-cli
    ]
  register: pip_installs

- include: hostname.yml
- include: docker.yml
  when: ansible_distribution == "Debian"
- include: users.yml
- include: ssh.yml
- include: tailscale.yml
  when: tailscale is defined and tailscale.enable
- include: firewall.yml
  when: firewall is defined and firewall.enable
- include: dotfiles.yml
- include: nix.yml

- include: desktop.yml
  when: desktop.enable
