---
- name: Install core packages
  apt:
    name: [
      python3,
      python3-pip,
      python3-distutils,
      python3-setuptools,
      cmake,
      htop,
      virtualenvwrapper,
      git,
      curl,
      nodejs,
      npm,
      net-tools,  # Contains netstat
      vim,
      sudo,
      apt-transport-https,
      zsh,
      keychain,
      unzip,
    ]
    state: present
    update_cache: yes
  become: yes
  become_user: root

  # TODO: only try to install on buster
  # TODO: install 'fd' on distros other than buster
- name: Install debian buster core packages
  apt:
    name: [fd-find]
    state: present
  become: yes
  become_user: root
  failed_when: false

- name: Symlink pip to pip3
  file:
    src: /usr/bin/pip3
    dest: /usr/bin/pip
    state: link
  become: yes

- name: Install Python packages
  pip:
    name: [virtualenvwrapper]
  register: pip_installs

- include: users.yml
- include: ssh.yml
- include: dotfiles.yml

- include: fail2ban.yml
  become: yes
  become_user: root

- include: tailscale.yml
  become: yes
  become_user: root
