---
- name: Place main config dir
  file:
    path: /etc/alex
    owner: alex
    group: alex
    state: directory
  become: true

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: arch.yml
  when: ansible_distribution == "Archlinux"

- name: Install Python packages
  pip:
    name: [
        virtualenvwrapper,
    ]
  when: development.enable
  register: pip_installs

- include: hostname.yml
  when: inventory_hostname != "localhost"
- include: users.yml
  tags: [users]
- include: systemd.yml
- include: nix.yml
  when: development.enable
- include: ssh.yml
# - include: promtail.yml
- include: tailscale.yml
  when: tailscale is defined and tailscale.enable
- include: firewall.yml
  when: firewall is defined and firewall.enable
- include: dotfiles.yml
- include: tmux.yml

- include: mail.yml
  tags: [mail]
  when: development.enable

- include: prometheus.yml
  when: inventory_hostname not in groups["k3s"]

- include: desktop.yml
  when: desktop is defined and desktop.enable
- include: gpu.yml
  when: desktop is defined and desktop.enable

- include: ansible.yml
