---
- name: Check if nix is installed
  stat:
    path: /nix
  register: nix_installed

- name: Install nix
  shell: "curl -L https://nixos.org/nix/install | sh"
  when: not nix_installed.stat.exists

# - name: Install cachix
#   command: nix profile install nixpkgs#cachix
#   notify: restart nix daemon

- name: Place nix.conf
  template:
    src: etc/nix/nix.conf
    dest: /etc/nix/nix.conf
    owner: root
    group: root
    mode: 0644
  become: true
  register: nix_conf

- name: Force restart nix daemon
  systemd:
    name: nix-daemon
    state: restarted
  become: true
  when: nix_conf.changed

# - name: Add cachix binary cache for devenv
#   command: cachix use devenv
#   notify: restart nix daemon

# - name: Install profile-wide packages
#   command: nix profile install --accept-flake-config tarball+https://install.devenv.sh/latest
#   notify: restart nix daemon
