---
- name: Create /nix
  file:
    path: /nix
    owner: alex
    group: alex
    mode: 0755
    state: directory
  become: true

- name: Check if nix command is available
  command: which nix
  register: nix_installed

- name: Install nix
  shell: "curl -L https://nixos.org/nix/install | sh"
  when: nix_installed.rc != 0
