---
- name: Create /nix
  file:
    path: /nix
    owner: alex
    group: alex
    mode: 0755
    state: directory
  become: true

- name: Check if nix is installed
  stat:
    path: /nix
  register: nix_installed

- name: Install nix
  shell: "curl -L https://nixos.org/nix/install | sh"
  when: not nix_installed.stat.exists
