---
- name: Create ssh dir
  file:
    path: /home/alex/.ssh
    state: directory
    owner: alex
    group: alex

- name: Get Github ssh keys
  uri:
    url: https://github.com/AlexanderGrooff.keys
    return_content: yes
  register: github_ssh_keys

- name: Define list of other known SSH keys
  set_fact:
    misc_ssh_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICxUS9/XrRGHBwta1NMwtFwH+uTkiqo06vXFz51PAJjd AWX

- name: Define total list of SSH keys
  set_fact:
    ssh_keys: "{{ github_ssh_keys['content'].split('\n') + misc_ssh_keys }}"

- name: Authorize ssh keys
  ansible.posix.authorized_key:
    user: alex
    exclusive: yes
    key: "{{ '\n'.join(ssh_keys) }}"
