---
- name: Add tailscale repo
  lineinfile:
    line: "deb https://pkgs.tailscale.com/stable/debian buster main"
    path: /etc/apt/sources.list.d/tailscale.list
    create: yes
    state: present

# See https://tailscale.com/kb/1041/install-debian-buster
- name: Add apt key for tailscale
  apt_key:
    url: https://pkgs.tailscale.com/stable/debian/buster.gpg
    state: present

- name: Install tailscale
  apt:
    name: tailscale
    update_cache: yes
  notify: restart-tailscaled

- name: Start tailscaled
  service:
    name: tailscaled
    state: started
    enabled: yes
