---
- name: Install Tailscale for Debian
  block:
    # See https://tailscale.com/kb/1041/install-debian-buster
    - name: Add apt key for tailscale
      apt_key:
        url: "https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.gpg"
        state: present
      become: true

    - name: Add tailscale repo
      apt_repository:
        repo: "deb https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
        state: present
      become: true

    - name: Install tailscale
      apt:
        name: tailscale
        update_cache: yes
        state: latest
      become: yes
      notify: restart-tailscaled
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install Tailscale for Arch
  kewlfft.aur.aur:
    name: tailscale
    state: present
  when: ansible_distribution == "Archlinux"

- name: Start tailscaled
  service:
    name: tailscaled
    state: started
    enabled: yes
  become: yes

- name: Check if tailscale is running
  shell: systemctl status tailscaled.service | grep 'Status:' | tail -n1 | awk '{for (i=2; i<=NF; i++) print $i}'
  register: tailscale_status

# TODO: This doesn't show any output if it's not yet connected and will hang.
- name: Connect tailscale via browser
  command: tailscale up
  become: yes
  when: '"Connected" not in tailscale_status.stdout and tailscale.auth_key is not defined'

- name: Connect tailscale with authtoken
  command: "tailscale up --authkey {{ tailscale.auth_key }}"
  become: yes
  when: '"Connected" not in tailscale_status.stdout and tailscale.auth_key is defined'

- name: Place sshd config
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
  become: yes
  notify: reload-ssh

- name: Enable sshd
  service:
    name: sshd
    enabled: yes
    state: started
  become: yes
  notify: reload-ssh
