---
# See https://tailscale.com/kb/1041/install-debian-buster
- name: Add apt key for tailscale
  apt_key:
    url: https://pkgs.tailscale.com/stable/debian/buster.gpg
    state: present

- name: Add tailscale repo
  apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/debian buster main"
    state: present

- name: Install tailscale
  apt:
    name: tailscale
    update_cache: yes
  notify: restart-tailscaled

- name: Start tailscaled
  service:
    name: tailscaled
    state: started
    enabled: yes

- name: Check if tailscale is running
  shell: systemctl status tailscaled.service | grep 'Status:' | tail -n1 | awk '{for (i=2; i<=NF; i++) print $i}'
  register: tailscale_status

- name: Connect tailscale
  command: tailscale up
  become: yes
  when: '"Connected" not in tailscale_status.stdout'
