---
- name: Create ~/.tmux/plugins
  file:
    path: ~/.tmux/plugins
    state: directory

- name: Clone tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    update: yes
