---
- name: Create alex group
  group:
    name: alex
    state: present
  become: yes

- name: Make alex group sudoer
  copy:
    content: '%alex ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: '/etc/sudoers.d/0pw4alex'
    mode: 0440
    validate: 'visudo -cf %s'
  become: yes

- name: Manage user alex
  user:
    name: alex
    groups:
      - alex
      - adm
    append: yes
    shell: /usr/bin/zsh
  become: yes

- name: Manage user root
  user:
    name: root
    state: present
    shell: /usr/bin/zsh
  become: yes

- name: Create local bin
  file: path=/home/alex/.local/bin state=directory owner=alex group=alex
