---
- name: Create alex group
  group:
    name: alex
    state: present
  become: yes

- name: Make alex group sudoer
  copy:
    content: '%alex ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: '/etc/sudoers.d/0pw4alex'
    mode: 0440
    validate: 'visudo -cf %s'
  become: yes

- name: Create alex user
  user:
    name: alex
    groups:
      - alex
      - adm
    state: present
  become: yes

- name: Create local bin
  file: path=/home/alex/.local/bin state=directory owner=alex group=alex

- name: Use ZSH for alex
  command: chsh -s /usr/bin/zsh alex
  become: yes

- name: Use ZSH for root
  command: chsh -s /usr/bin/zsh root
  become: yes
