---
# TODO: Clone awx and change configs

- name: Set awx nginx config
  template:
    src: nginx/awx.conf
    dest: /etc/nginx/sites-enabled/awx.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  become_user: root
  notify: reload-nginx

- name: Check if certificate exists
  stat: path=/etc/letsencrypt/live/awx.agrooff.com/fullchain.pem
  become: yes
  become_user: root
  register: cert_path

- name: Generate letsencrypt certificates
  command: certbot certonly -d awx.agrooff.com --nginx -m alexandergrooff@gmail.com --agree-tos -n
  become: yes
  become_user: root
  when: not cert_path.stat.exists
