---
# Ripped off from https://github.com/vandot/ansible-role-k3sup, don't want to use galaxy
- name: Get the latest release version from GitHub
  uri:
    url: "{{ k3sup_github_api_releases }}"
    return_content: true
    body_format: json
  register: k3sup_latest_release

- name: Ensure the release version is set as a fact
  set_fact:
    k3sup_release_version: "{{ k3sup_latest_release.json.tag_name }}"
- name: Ensure suffix information is set as a fact
  set_fact:
    k3sup_suffix: "{{ k3sup_arch_map[ansible_architecture].suffix }}"

- name: Ensure URLs are set as facts for downloading binaries
  set_fact:
    k3sup_binary_url: "{{ k3sup_github_download_url }}/{{ k3sup_release_version }}/k3sup{{ k3sup_suffix }}"
    k3sup_hash_url: "{{ k3sup_github_download_url }}/{{ k3sup_release_version }}/k3sup{{ k3sup_suffix }}.sha256"

- name: Ensure the k3sup hashsum is downloaded
  uri:
    url: "{{ k3sup_hash_url }}"
    return_content: true
  register: k3sup_hash_sum_raw

- name: Ensure sha256sum is set from hashsum variable
  set_fact:
    k3sup_hash_sum: "{{ (k3sup_hash_sum_raw.content.split('\n') | select('search', 'k3sup') | first).split() | first }}"
  changed_when: false

- name: Ensure installation directory exists
  file:
    path: "{{ k3sup_install_dir }}"
    state: directory

- name: Ensure k3sup binary is installed
  get_url:
    url: "{{ k3sup_binary_url }}"
    dest: "{{ k3sup_install_dir }}/k3sup"
    checksum: "sha256:{{ k3sup_hash_sum }}"
    mode: 0755
  when: k3sup_non_root is defined and k3sup_non_root

- name: Ensure k3sup binary is installed (root)
  get_url:
    url: "{{ k3sup_binary_url }}"
    dest: "{{ k3sup_install_dir }}/k3sup"
    checksum: "sha256:{{ k3sup_hash_sum }}"
    mode: 0755
  become: true
  when: k3sup_non_root is not defined or not k3sup_non_root
