---
- name: Create k3s group
  group:
    name: "{{k3s_username}}"
    system: yes
    state: present
  become: yes

- name: Make k3s group sudoer
  copy:
    content: '%{{k3s_username}} ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: '/etc/sudoers.d/0pw4{{k3s_username}}'
    mode: 0440
    validate: 'visudo -cf %s'
  become: yes

- name: Create k3s user
  user:
    name: "{{k3s_username}}"
    group: "{{k3s_username}}"
    system: yes
    password: '!'
    state: present
  become: yes

- name: Ensure ssh directory
  file:
    path: "/home/{{k3s_username}}/.ssh"
    state: directory
    owner: "{{k3s_username}}"
    group: "{{k3s_username}}"
  become: yes

- name: Authorize github ssh keys for k3s user
  get_url:
    url: https://github.com/AlexanderGrooff.keys
    dest: "/home/{{k3s_username}}/.ssh/authorized_keys"
  become: yes

- include: k3sup.yml
