- name: Enable ip_vs kernel module
  lineinfile:
    path: /etc/modules
    line: "modprobe ip_vs"
    create: yes
    state: present
  become: true
  register: ip_vs_module
  tags: [keepalived]

- name: Modprobe if needed
  command: modprobe ip_vs
  when: ip_vs_module.changed
  become: true
  tags: [keepalived]

- name: Setup keepalived in container
  docker_container:
    name: keepalived
    image: osixia/keepalived:2.0.20
    restart_policy: always
    capabilities:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    network_mode: host
    env:
      KEEPALIVED_UNICAST_PEERS: "#PYTHON2BASH:['{{ tailscale_ip }}']"
      KEEPALIVED_VIRTUAL_IPS: "{{ floating_ip }}"
      KEEPALIVED_PRIORITY: "200"
  become: true
  tags: [keepalived]
