- name: Install pip libraries library
  pip:
    name: "{{ item }}"
    state: present
  with_items:
  - docker==6.1.1
  - jsondiff==2.0.0
  become: true

- include: keepalived.yml
  tags: [keepalived]

# Only do this once
# - name: Initialize Docker swarm
#   community.docker.docker_swarm:
#     state: present
#     advertise_addr: "{{ tailscale_ip }}"
#     labels: "{{ labels | default({}) }}"
#   become: true

- name: Create public network
  community.docker.docker_network:
    state: present
    name: traefik-public
    driver: overlay
    attachable: true
  become: true

- name: Set node labels
  community.docker.docker_node:
    hostname: "{{ inventory_hostname }}"
    labels: "{{ labels | default({}) }}"
  become: true

- name: Ensure dirs exist before mounting in Docker
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  become: true
  with_items:
  - {path: /data/swarm}
  - {path: /data/swarm/authelia}
  - {path: /data/swarm/authelia/config}
  - {path: /data/swarm/traefik}
  - {path: /data/swarm/traefik/config}
  - {path: /data/swarm/vault}  # vault user in container
  - {path: /data/swarm/vault/data, owner: "100"}  # vault user in container
  - {path: /data/swarm/vault/config, owner: "100"}  # vault user in container
  - {path: /data/swarm/home-assistant}
  - {path: /data/swarm/home-assistant/config}

- name: Ensure files exist before mounting in Docker
  file:
    path: "{{ item.path }}"
    state: touch
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  become: true
  loop:
  - {path: /data/swarm/traefik/traefik.log}
  - {path: /data/swarm/traefik/access.log}
  - {path: /data/swarm/traefik/acme.json, mode: "0600"}
  - {path: /data/swarm/vault/data/vault.db, mode: "0600", owner: "100"}

- include_tasks:
    file: setup_stack.yml
    apply:
      tags: [apps]
  tags: [apps]
  loop_control:
    loop_var: stack
  loop:
  - name: "vault"
    files:
      - {src: vault/config/config.hcl.j2, dest: /data/swarm/vault/config/config.hcl}
  - name: "authelia"
    secrets: "{{ authelia.secrets }}"
    files:
      - {src: authelia/config/configuration.yml.j2, dest: /data/swarm/authelia/config/configuration.yml}
      - {src: authelia/config/users_database.yml.j2, dest: /data/swarm/authelia/config/users_database.yml}
  - name: "traefik"
    files:
      - {src: traefik/config/traefik.toml.j2, dest: /data/swarm/traefik/config/traefik.toml}
  - name: "home-assistant"
    files: []
