---
- name: Find existing secret
  shell: docker secret ls | awk '{print$2=="{{ secret.key }}"}' | grep 1
  register: secret_info
  failed_when: false
  changed_when: false
  become: true

- name: Create secret for service {{ stack.name }}
  community.docker.docker_secret:
    state: present
    name: "{{ secret.key }}"
    data: "{{ secret.value or lookup('password', '/dev/null', length=50, chars=['ascii_letters', 'digits']) }}"
    labels:
      stack: "{{ stack.name }}"
  when: secret_info.rc != 0
