---
- name: Upload config file {{ item }}
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: alex
    group: alex

- name: Apply Kubernetes config file {{ item }}
  k8s:
    state: present
    src: "/tmp/{{ item }}"
