---
- name: Add {{ item.name }} chart repo
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.repo_url }}"

- name: Upload helm values file {{ item.name }}
  template:
    src: "helm/{{ item.name }}.yaml.j2"
    dest: "/tmp/{{ item.name }}.yaml"
    owner: alex
    group: alex

- name: Deploy {{ item.name }}
  kubernetes.core.helm:
    name: "{{ item.name }}"
    chart_ref: "{{ item.name }}/{{ item.name}}"
    release_namespace: "{{ item.name }}"
    create_namespace: true
    values_files: "/tmp/{{ item.name }}.yaml"
