---
- name: Get AWX operator config
  git:
    repo: https://github.com/ansible/awx-operator.git
    version: 0.15.0
    dest: ~/code/awx-operator
    accept_hostkey: yes
    update: no
  register: awx_operator_code

- name: Deploy AWX operator
  command: make deploy
  args:
    chdir: ~/code/awx-operator
  when: awx_operator_code.changed

- include: apply_config.yml
  with_items:
  - awx.yaml.j2
