---
- include_tasks:
    file: apply_helm.yml
    apply:
      tags: [apps]
  tags: [apps]
  with_items:
  - name: prometheus
    repo_url: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    chart_version: 15.12.0
  - name: metallb
    repo_url: https://metallb.github.io/metallb
    chart_version: 0.13.4
  - name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
    chart_version: 4.2.1
  - name: cert-manager
    repo_url: https://charts.jetstack.io
    chart_version: 1.9.1
  - name: harbor
    repo_url: https://helm.goharbor.io
    namespace: harbor
    chart_version: 1.11.0
  - name: coredns
    repo_url: https://coredns.github.io/helm
    namespace: coredns
    chart_version: 1.19.4
  - name: grafana
    repo_url: https://grafana.github.io/helm-charts
    namespace: monitoring
    chart_version: 6.32.14
  - name: loki
    repo_url: https://grafana.github.io/helm-charts
    namespace: monitoring
    chart_version: 2.14.1
  - name: promtail
    repo_url: https://grafana.github.io/helm-charts
    namespace: monitoring
    chart_version: 6.2.3
  - name: pricewatcher
    repo_url: https://harbor.alex.systems/chartrepo/pricewatcher
    repo_username: "{{ harbor.robot.username }}"
    repo_password: "{{ harbor.robot.password }}"

- include_tasks:
    file: apply_config.yml
    apply:
      tags: [apps]
  tags: [apps]
  with_items:
  - metallb-config.yaml.j2
  - cloudflare-secret.yaml.j2
  - issuer.yaml.j2
  - airflow_admin_rolebinding.yaml.j2

# Bit of a hack: we copy the files to the PVC that was just created
# Ideally we'd use git-sync, but that's too much work for now
#- name: Copy over DAGs to Airflow volume
#  kubernetes.core.k8s_cp:
#    namespace: airflow
#    pod: airflow-worker-0
#    remote_path: "/opt/airflow/dags/{{ item | basename }}"
#    local_path: "{{ item }}"
#    container: worker
#  with_fileglob:
#  - files/airflow/dags/*

- include: freqtrade.yml
  tags: [apps]
