- name: Place user service file
  template:
    src: "config/systemd/user/{{ service_name }}.service"
    dest: "/home/alex/.config/systemd/user/{{ service_name }}.service"
    owner: alex
    group: alex

- name: Start user service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes
    scope: user
    daemon_reload: yes
