---
k3s_username: 'k3s'

# k3sup

### Package
# k3sup state, options: installed, uninstalled
# (default: installed)
k3sup_state: installed

# Use a specific k3sup version, if set to "false" we will get the latest
# k3sup_release_version: 0.7.0
k3sup_release_version: false

# Install k3sup as a non-root user
k3sup_non_root: false

# URL for GitHub project
k3sup_github_url: https://github.com/alexellis/k3sup

# Installation directory for k3sup
k3sup_install_dir: /usr/local/bin

k3sup_github_api: "{{ k3sup_github_url | replace('github.com', 'api.github.com') }}"
k3sup_github_api_releases: "{{ k3sup_github_api | replace('.com', '.com/repos') }}/releases/latest"
k3sup_github_download_url: "{{ k3sup_github_url }}/releases/download"

k3sup_arch_map:
  amd64:
    suffix: ""
  x86_64:
    suffix: ""
  arm64:
    suffix: "-arm64"
  aarch64:
    suffix: "-arm64"
  arm:
    suffix: "-armhf"
  arm7:
    suffix: "-armhf"
  armv7l:
    suffix: "-armhf"
  armhf:
    suffix: "-armhf"
k3sup_os_map:
  Windows:
    suffix: ".exe"
  Darwin:
    suffix: "-darwin"

