---
# https://wiki.hyprland.org/Getting-Started/Installation/
- name: Install Hyprland desktop packages for Arch
  kewlfft.aur.aur:
    name: [
      # TODO: switch to hyprland if nvidia not found
      hyprland-nvidia,
      grim,  # required for the screenshot portal to function
      hyprpaper,
      qt5-wayland,
      qt6-wayland,
      slurp,  # support for interactive mode for the screenshot portal
      xdg-desktop-portal-hyprland,  # XDP is a program that lets other applications communicate swiftly with the compositor through D-Bus.

      # Wayland tools
      dunst,  # Notifications
      grimshot,  # Screenshot tool like flameshot
      pipewire,  # Sound & screensharing
      swaylock,
      waybar-module-pacman-updates-git,
      waybar,
      wireplumber,  # Sound & screensharing
      wl-clipboard,  # Images in clipboard with wl-copy
      wofi,  # Rofi but wayland
    ]
  when: ansible_distribution == "Archlinux"

- name: Remove redundant packages
  pacman:
    name: [
      xdg-desktop-portal-gnome,
    ]
  when: ansible_distribution == "Archlinux"
  become: yes

- name: Ensure waybar reload service is running
  systemd:
    name: "waybar-reload"
    state: started
    enabled: yes
    scope: user
    daemon_reload: yes

# (1/2) installing sway                                                 [#######################################] 100%
# Sway requires additional setup for privilege escalation. Without this setup,
# sway will fail to start with session activation permission failures. Choose one
# of the two available options (In alphabetical, not recommended, order):
#
# 1. polkit: This will make sway "just work" right after installation but may be
#            a weightier solution than desired.
#
# 2. seatd: Already required as a sway dependency, this is a lighter-weight
#           solution but requires some user configuration: Enabling the service,
#           adding your user to the "seat" group, then logging out/in again.
#
# Either option should provide the same functionality/stability. Refer to the
# Sway wiki page for information.
# Optional dependencies for sway
#     bemenu: Wayland-native alternative to dmenu
#     dmenu: Application launcher used in default config [installed]
#     foot: Terminal emulator used in the default configuration
#     i3status: Status line generation [installed]
#     mako: Lightweight notification daemon
#     polkit: System privilege control. Required if not using seatd service [installed]
#     swaybg: Wallpaper tool for sway
#     swayidle: Idle management daemon
#     swaylock: Screen locker
#     waybar: Highly customizable bar [installed]
#     xorg-xwayland: X11 support [installed]
# (2/2) installing weston                                               [#######################################] 100%
# Optional dependencies for weston
#     xorg-xwayland: support x11 backend [installed]
#     libpipewire: support pipewire backend [installed]
#     freerdp: support rdp backend
#     neatvnc: support vnc backend





# (1/1) installing grimshot                                             [#######################################] 100%
# Optional dependencies for grimshot
#     libnotify: Notify users when a screenshot is taken [installed]
#     wl-clipboard: Copy screenshots
