- name: Install Pantheon DE
  kewlfft.aur.aur:
    name: [
      # https://wiki.archlinux.org/title/Pantheon
      pantheon-session,  # Core components
      elementary-icon-theme,
      elementary-wallpapers,
      gala,
      gtk-theme-elementary,
      lightdm-pantheon-greeter,
      pantheon-applications-menu,
      pantheon-calculator,
      pantheon-calendar,
      pantheon-default-settings,
      pantheon-files,
      pantheon-polkit-agent,
      pantheon-print,  # Print settings dialog
      pantheon-settings-daemon,
      plank,
      switchboard-plug-a11y,
      switchboard-plug-applications,
      switchboard-plug-display,
      switchboard-plug-keyboard,
      switchboard-plug-mouse-touchpad,
      switchboard-plug-networking,
      switchboard-plug-notifications,
      switchboard-plug-online-accounts,
      switchboard-plug-power,
      switchboard-plug-printers,
      switchboard-plug-security-privacy,
      switchboard-plug-sharing,
      switchboard-plug-sound,
      switchboard-plug-useraccounts,
      switchboard-plug-users,
      switchboard,  # Settings manager
      ttf-droid,
      ttf-opensans,
      ttf-roboto,
      wingpanel-indicator-bluetooth,
      wingpanel-indicator-datetime,
      wingpanel-indicator-keyboard,
      wingpanel-indicator-network,
      wingpanel-indicator-notifications,
      wingpanel-indicator-power,
      wingpanel-indicator-session,
      wingpanel-indicator-sound,
      wingpanel,  # Top panel
    ]

- name: Verify elementary greeter exists
  stat:
    path: /usr/share/xgreeters/io.elementary.greeter.desktop
  register: greeter
  failed_when: greeter.stat.exists == False

- name: Set lightdm greeter
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#?greeter-session=.*$'
    line: 'greeter-session=io.elementary.greeter'
    state: present
  become: true
  when: greeter.stat.exists == True

- name: Place Plank autostart
  template:
    src: etc/xdg/autostart/pantheon-plank.desktop
    dest: /etc/xdg/autostart/pantheon-plank.desktop
  become: true

- name: Disable dunst
  systemd:
    name: dunst.service
    enabled: false
    state: stopped
    scope: user
