    - name: Install sway
      apt:
        name: [
          grimshot,  # Screenshot tool
          sway,
          swaylock,
          wdisplays,
          weston,  # Compositor
        ]
        state: latest
      become: true
      when: ansible_os_family == "Debian"
