---
- name: Check if k3s is already running
  service:
    name: k3s
    state: started
  register: start_k3s
  ignore_errors: true  # Will error if not installed, that's fine

- include: install.yml
  when: not start_k3s is succeeded

# TODO: FIGURE THIS OUT
#- name: Accept keys of slaves
#  authorized_key:
#    user: "{{k3s_username}}"
#    key: "{{item['ssh_pubkey']}}"
#    state: present
#  with_items:
#  - "{{k3s_slaves}}"

- include: helm.yml
