---
- name: Clone zenbot
  git:
    repo: git://github.com/deviavir/zenbot.git
    dest: /home/alex/zenbot
    accept_hostkey: yes
    update: yes
    force: yes
  register: update_zenbot

- name: Place zenbot config
  template:
    src: zenbot/conf.js
    dest: /home/alex/zenbot/conf.js

- name: Install dependencies
  npm:
    path: /home/alex/zenbot
  when: update_zenbot.changed

- name: Place executable
  template:
    src: zenbot/zenbot.sh
    dest: /home/alex/.local/bin/zenbot
    owner: alex
    group: alex
    mode: 0755
