---
- name: Install php fpm and modules
  apt:
    package: [
    'php7.3-fpm',
    'php7.3-bz2',
    'php7.3-ctype',
    'php7.3-curl',
    'php7.3-dom',
    'php7.3-fileinfo',
    'php7.3-gd',
    'php7.3-iconv',
    'php7.3-imagick',
    'php7.3-intl',
    'php7.3-json',
    'php7.3-mbstring',
    'php7.3-memcached',
    'php7.3-posix',
    'php7.3-xml',
    'php7.3-zip']
    state: present
  become: yes
  become_user: root
  notify: restart-php
