---
- name: Check if vundle is installed
  stat:
    path: ~/.vim/bundle/Vundle.vim
  register: vundle

- name: Clone vundle package
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
  when: vundle.stat.exists == false

- name: Clone fzf package
  git: repo=https://github.com/junegunn/fzf.git depth=1 update=no dest=~/.apps/fzf
  register: fzf_updated

  # TODO: add handler for installing vim plugins
- name: Install fzf
  command: ~/.apps/fzf/install --completion --no-key-bindings --update-rc
  when: fzf_updated.changed

- name: Symlink fzf to path
  file: src=~/.apps/fzf/bin/fzf dest=~/.local/bin/fzf state=link
