---
- name: Ensure data dir exists
  file:
    path: /data
    owner: root
    group: root
    state: directory
    mode: 0755
  become: yes

- name: Ensure data dir for consul exists
  file:
    path: /data/consul
    owner: consul
    group: consul
    state: directory
    mode: 0775
  become: yes

- name: Place certificate files
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: consul
    group: consul
    mode: 0640
  become: yes
  with_items:
  - "etc/consul.d/consul-agent-ca.pem"
  - "etc/consul.d/{{ inventory_hostname }}.pem"
  - "etc/consul.d/{{ inventory_hostname }}-key.pem"

- name: Place consul config files
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: consul
    group: consul
    mode: 0644
  become: yes
  with_items:
  - etc/consul.d/consul.hcl
  notify: restart-consul

- name: Place root config files
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  become: yes
  with_items:
  - etc/systemd/system/consul.service
  notify:
  - reload-systemd
  - restart-consul
  - restart-nomad

- name: Start consul service
  systemd:
    name: consul
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes
