---
- name: Allow traffic on tailscale
  community.general.ufw:
    rule: allow
    src: "100.64.0.0/10"
  become: true

- name: Allow all access from RFC1918 networks to this host
  community.general.ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  become: true

- name: Allow everything on loopback
  community.general.ufw:
    rule: allow
    src: "127.0.0.1/32"
  become: true

- name: Default to deny all traffic
  community.general.ufw:
    state: enabled
    policy: deny
  become: true