---
- name: Allow from port 80, 443
  community.general.ufw:
    rule: allow
    from_port: '{{ item }}'
  loop:
    - "80"
    - "443"
  become: true
  notify: reload-ufw

- name: Allow to port 80, 443
  community.general.ufw:
    rule: allow
    to_port: '{{ item }}'
  loop:
    - "80"
    - "443"
  become: true
  notify: reload-ufw
