- name: Add hashicorp apt-key
  apt_key:
    id: E8A032E094D8EB4EA189D270DA418C88A3219F7B
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: yes

- name: Add hashicorp repository into sources list
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  become: yes

- name: Install nomad
  apt:
    package: nomad
    update_cache: yes
  become: yes

- name: Add user to group nomad
  user:
    name: alex
    groups:
      - nomad
    append: yes
    state: present
  become: yes
