---
- name: Install consul
  apt:
    package: consul
  become: yes

- name: Add user to group consul
  user:
    name: alex
    groups:
      - consul
    append: yes
    state: present
  become: yes
