---
- name: Place nomad job {{ item }}
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: nomad
    group: nomad
    mode: 0644
  become: yes
  register: job_placed
  tags: ["jobs"]

- name: Validate job {{ item }}
  command: "nomad job validate /{{ item }}"
  tags: ["jobs"]
  changed_when: false

- name: Get job info of {{ item }}
  shell: "nomad job plan /{{ item }} | grep 'Job: ' | cut -d\\\" -f2"
  register: job_info
  tags: ["jobs"]
  failed_when: false  # This seems to always returns rc 1. Idk why?
  changed_when: false

- name: Get job ID
  set_fact:
    job_id: "{{ job_info.stdout | trim }}"
  tags: ["jobs"]
  changed_when: false

- name: Check current job status
  shell: "nomad job status {{ job_id }} | grep Status | grep running"
  register: job_status
  tags: ["jobs"]
  failed_when: false  # Never fail because we want to see the exitcode
  changed_when: false

- name: Run job {{ item }}
  command: "nomad job run /{{ item }}"
  when: job_placed.changed or job_status.rc != 0
  tags: ["jobs"]
