---
- name: Place nomad job files
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: nomad
    group: nomad
    mode: 0644
  become: yes
  with_items:
  - nomad/jobs/webapp.nomad
  - nomad/jobs/nginx.nomad

- name: Run all jobs
  command: "nomad job run {{ item }}"
  with_items:
  - /nomad/jobs/nginx.nomad
  - /nomad/jobs/webapp.nomad