---
- include: firewall.yml
- include: setup-apt.yml
- include: install-consul.yml
- include: configure-consul.yml
- include: install-nomad.yml
- include: configure-nomad.yml
- include: jobs.yml
  with_items:
  - nomad/jobs/webapp.nomad
  - nomad/jobs/nginx.nomad
