---
- name: Ensure cni dir exists
  file:
    path: /opt/cni/bin
    recurse: yes
    state: directory
  become: yes
  register: make_dir

- name: Download plugins
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.0.1/cni-plugins-linux-amd64-v1.0.1.tgz
    dest: /tmp/cni-plugins.tgz
  when: make_dir.changed

- name: Extract bin
  unarchive:
    src: /tmp/cni-plugins.tgz
    dest: /opt/cni/bin
    remote_src: true
    creates: /opt/cni/bin/bridge
  become: true
  when: make_dir.changed

- name: Persistent bridge networking
  lineinfile: 
    path: /etc/sysctl.d/bridge-networking.conf
    line: "{{ item }}"
    create: yes
    state: present
  become: yes
  register: set_persistent_networking
  with_items:
  - "net.bridge.bridge-nf-call-arptables = 1"
  - "net.bridge.bridge-nf-call-ip6tables = 1"
  - "net.bridge.bridge-nf-call-iptables = 1"

- name: Allow bridge networking
  shell: "{{ item }}"
  become: yes
  when: set_persistent_networking.changed
  with_items:
  - "echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-arptables"
  - "echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-ip6tables"
  - "echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-iptables"
