---
- name: Place files into static volume
  template:
    src: "static/{{ item | basename }}"
    dest: "/data/shared/nomad/static/{{ item | basename }}"
  with_fileglob:
  - templates/static/*
  become: yes
