---
- block:
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Plex apt key (Ubuntu & Debian with systemd)
      apt_key:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key
        state: present

    - name: Add Plex apt repo (Ubuntu & Debian with systemd)
      apt_repository:
        repo: deb https://downloads.plex.tv/repo/deb public main
        state: present
      changed_when: false

    - name: Apt install Plex
      apt:
        name: plexmediaserver
        state: present
        update_cache: true
      notify: restart plex

  when: ansible_os_family == "Debian"
  become: true
  become_user: root

- name: Autostart Plex and start service
  service:
    name: plexmediaserver
    enabled: true
  become: yes
  become_user: root
  notify: restart plex

- name: Check if certificate exists
  stat: path=/etc/letsencrypt/live/plex.agrooff.com/fullchain.pem
  become: yes
  become_user: root
  register: cert_path

- name: Generate letsencrypt certificates
  command: certbot certonly -d plex.agrooff.com --nginx -m alexandergrooff@gmail.com --agree-tos -n
  become: yes
  become_user: root
  when: not cert_path.stat.exists

- name: Set plex nginx config
  template:
    src: nginx/plex.conf
    dest: /etc/nginx/sites-enabled/plex.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  become_user: root
  notify: reload-nginx
