---
- name: Enable bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    reload: yes
  become: yes

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
  become: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  become: yes
  when: ansible_all_ipv6_addresses

- name: Create k3s group
  group:
    name: "{{ k3s_username }}"
    system: yes
    state: present
  become: yes

- name: Make k3s group sudoer
  copy:
    content: '%{{ k3s_username }} ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: '/etc/sudoers.d/0pw4{{ k3s_username }}'
    mode: 0440
    validate: 'visudo -cf %s'
  become: yes

- name: Create k3s user
  user:
    name: "{{ k3s_username }}"
    group: "{{ k3s_username }}"
    system: yes
    password: '!'
    state: present
  become: yes

- name: Create .kube dir
  file: 
    path: ~/.kube
    recurse: true
    state: directory

- include: packages.yml

- name: Place floating IP networking config
  template:
    src: etc/network/interfaces.d/60-floating-ip.cfg
    dest: /etc/network/interfaces.d/60-floating-ip.cfg
  become: yes
  notify: restart-networking
