---
- name: Ensure required packages are installed
  apt:
      state: present
      package: [
          'open-iscsi', # Required for longhorn
      ]
  become: yes

- name: Install Kubernetes Python packages
  pip:
    name: [
        kubernetes==21.7.0,  # Needed for the k8s galaxy collection
        requests==2.27.1,
    ]
  register: pip_installs
